name: dart_mongo_lite
description: Dart MongoLite a library to use mongo, without a server.
version: 0.1.0-beta.2
homepage: https://github.com/KaikyuDev/dart_mongo_lite

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.10
